version: '3.4'

services:
  api:
    image: webdevops/php-nginx:alpine-php7
    restart: "no"
    working_dir: /var/www
    depends_on:
      - mysql
    volumes:
      - $PWD/src:/var/www
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
      - WEB_DOCUMENT_INDEX=index.php
      - WEB_ALIAS_DOMAIN=localhost
    ports:
      - 80:80
    networks:
      - pureftpd

  mysql:
    image: mariadb:10.3
    restart: "no"
#    volumes:
#      - $PWD/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=pureftpd
      - MYSQL_USER=pure
      - MYSQL_PASSWORD=pure
# only allow exposed port for debug!
    ports:
      - 3306:3306
    networks:
      - pureftpd

  ftp:
    build: ./ftp
    restart: "no"
    depends_on:
      - mysql
    volumes:
      - $PWD/ftp/config:/etc/pureftpd
#      - /var/ftp-data:/var/ftp-data
    ports:
      - 20-21:20-21
      - 30000-30999:30000-30999
    networks:
      - pureftpd

networks:
  pureftpd: